In [ ]:
import pandas as pd
import numpy as np
import torch
import json
import gc
gc.collect()
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
dataTruth = pd.read_json("/content/drive/MyDrive/pan20-authorship-verification-training-small-truth.jsonl", lines=True)

In [ ]:
dataTruth.head()

id  same             authors
0  6cced668-6e51-5212-873c-717f2bc91ce6  True  [1446633, 1446633]
1  3c6c188a-db28-59aa-8c09-3d0f799ff579  True  [1446633, 1446633]
2  b0cfa94f-c9ec-5aa5-8331-a5a249b664cf  True  [1446633, 1446633]
3  e6e86e73-9a7b-58f2-a652-a17b4a1bcabf  True  [1446633, 1446633]
4  4fe541af-912e-5a86-81a5-94c6d3891509  True  [1446633, 1446633]

In [ ]:
with open('/content/drive/MyDrive/pan20-authorship-verification-training-small.jsonl') as json_file:      
    data = json_file.readlines()
    data = list(map(json.loads, data))
    json_file.close()

data = pd.DataFrame(data)

In [ ]:
data.head()

id  \
0  6cced668-6e51-5212-873c-717f2bc91ce6   
1  3c6c188a-db28-59aa-8c09-3d0f799ff579   
2  b0cfa94f-c9ec-5aa5-8331-a5a249b664cf   
3  e6e86e73-9a7b-58f2-a652-a17b4a1bcabf   
4  4fe541af-912e-5a86-81a5-94c6d3891509   

                                          fandoms  \
0  [Guardians of Ga'Hoole, Hetalia - Axis Powers]   
1               [Guardians of Ga'Hoole, Warriors]   
2       [Guardians of Ga'Hoole, Xiaolin Showdown]   
3               [Hetalia - Axis Powers, Warriors]   
4       [Hetalia - Axis Powers, Xiaolin Showdown]   

                                                pair  
0  [I shift a bit, warily letting my eyes dart fr...  
1  [I shift a bit, warily letting my eyes dart fr...  
2  [A single tear escaped me as I left. I did hav...  
3  ["Ja." Ludwig kept his gaze upon her, solidly....  
4  [And he did. Slowly, hesitantly...but coming f...

In [ ]:
labels = dataTruth["same"]
labels

0         True
1         True
2         True
3         True
4         True
         ...  
52596    False
52597    False
52598    False
52599    False
52600    False
Name: same, Length: 52601, dtype: bool

In [ ]:
labels = pd.concat([labels[:len(labels)//10+1000], labels[-len(labels)//10+200:]])
labels

0         True
1         True
2         True
3         True
4         True
         ...  
52596    False
52597    False
52598    False
52599    False
52600    False
Name: same, Length: 11321, dtype: bool

In [ ]:
data = data["pair"]
data = pd.concat([data[:len(data)//10+1000], data[-len(data)//10+200:]])
data1 = []
data2 = []

In [ ]:
data

0        [I shift a bit, warily letting my eyes dart fr...
1        [I shift a bit, warily letting my eyes dart fr...
2        [A single tear escaped me as I left. I did hav...
3        ["Ja." Ludwig kept his gaze upon her, solidly....
4        [And he did. Slowly, hesitantly...but coming f...
                               ...                        
52596    [Enjoy! And time stands still beneath the air ...
52597    ["I forgive you," she blurted out looking stra...
52598    ["What? Why? What"s happening? Where are we go...
52599    ["Gah!" I growled. "I need a password to acces...
52600    [Chica heard a noise below her and saw Golden ...
Name: pair, Length: 11321, dtype: object

In [ ]:
for i in data:
  # print(i)
  data1.append(i[0])
  data2.append(i[1])

In [ ]:
del data
del dataTruth
gc.collect()

252

In [ ]:
labels

0         True
1         True
2         True
3         True
4         True
         ...  
52596    False
52597    False
52598    False
52599    False
52600    False
Name: same, Length: 11321, dtype: bool

In [ ]:
l = []
for i in labels:
  if i == True:
    l.append(1)
  else: 
    l.append(0)

In [ ]:
labels = l

In [ ]:
labels[0]

1

In [ ]:
v = list(zip(data1, data2))

In [ ]:
v[0]

('I shift a bit, warily letting my eyes dart from one owl to the other -- but my eyes are trained on the Barn Owl the most. Like Hoole...so like Hoole... He turns a bit, and our eyes meet directly. I can"t describe it...in this next moment, I don"t look away, how awkward it seems. I stare into his eyes. They"re like Hoole"s... They are Barn Owl eyes, but Hoole"s eyes. They"re his eyes...Hoole"s eyes... They hold that light of valor, justice, that one glow that I always made me feel my gizzard twitch in the bottom of my heart. Hoole... He never wanted me, did he? He loved me, but only who I was pretending to be. He never loved me, only Emerilla...lucky owl. I just wanted to belong -- because I was nothing -- and he gave me that. He was so fair, so kind...he gave me something even Kreeth could not. Mum and Da -- Ygryk and Pleek -- were supposed to be my parents. I was supposed to be their chick, Lutta. Yet they left me. They talked about me behind my back...I was a freak. My own parents 

In [ ]:
from sklearn.model_selection import train_test_split

train_x, valid_x, train_y, valid_y = train_test_split(v, labels, test_size=0.2, random_state=800, shuffle=True)

In [ ]:
train_x1, train_x2 = zip(*train_x)

In [ ]:
valid_x1, valid_x2 = zip(*valid_x)

In [ ]:
train_x1[0]

'"I"m Adrien," he says. "Oh I know." With that she pulls the gear into drive and turns out of the yard. Adrien stretches his neck to see his father and Gorilla one last time. But only Gorilla stands there, and his father slams the door behind him as he walks into the house. Tears well at Adrien"s eyes, but he wipes them away quickly as he watches his home leave his life forever. Hey readers! Thank you for clicking on the story and reading it! Just a couple things to tell you about my story - The character POV switches throughout the story, but is based off of Marinette and Adrien. - I will be using season one and two references from the show for some of the chapters, but not everything will be the same. I thought it"d be appropriate to make Adrien a lover of stories and books since his video games and anime are unavailable to him. I hope you guys enjoy this AU! A/N : I do not own Miraculous Ladybug Marinette"s pencil lead breaks as she accidently presses it to roughly into the paper. S

In [ ]:
train_x2[0]

'Rise sucked in a small string of noodle, swallowed quickly, and leaned forward. "You mean - you think he was talking about Personas?" They stopped talking abruptly then, for the cook approached with Narukami"s ramen. The team leader thanked him, and they all remained silent until he had passed out of earshot. "It makes sense," Narukami said. He blew lightly on the surface of his steaming soup bowl. "If anyone were to take advantage of or try to aggravate any part of this situation, it"d have to be someone who knows about the Dark Hour, and that pretty much narrows it down to people involved in Kirijo"s research and other Persona-users. And we know that a person doesn"t need to be a saint to control their Shadow; Adachi had a Persona, too. So this cult, or more specifically the person behind it - anything we can figure out about them could be a vital piece of the puzzle." "So what do we know?" Chie asked, looking to Naoto. Teddie slurped down another bowl and called for a fifth, either

In [ ]:
train_y[0]

0

In [ ]:
# preprocess

train_x1 = list(train_x1)

train_x2 = list(train_x2)

In [ ]:
from collections import Counter
from torchtext.vocab import vocab

In [ ]:
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer('spacy')

In [ ]:
counter = Counter()

for line in train_x1:
    counter.update(tokenizer(line))
vocab_1 = vocab(counter, min_freq=10, specials=('<unk>', '<BOS>', '<EOS>', '<PAD>'))

In [ ]:
counter = Counter()

for line in train_x2:
    counter.update(tokenizer(line))
vocab_2 = vocab(counter, min_freq=10, specials=('<unk>', '<BOS>', '<EOS>', '<PAD>'))

In [ ]:
default_index = -1

vocab_1.set_default_index(default_index)
vocab_2.set_default_index(default_index)

In [ ]:
def tosize(a, n, vcb):
  a = np.asarray(a)
  x = np.array([vcb["<PAD>"]] * n, dtype=a.dtype)
  m = min(n, len(a))
  x[:m] = a[:m]
  return x

def text_transform_1(x):
  inner =  [vocab_1[token] for token in tokenizer(x)]

  inner = tosize(inner, 4096, vocab_1)

  return [vocab_1['<BOS>']] + inner + [vocab_1['<EOS>']]

def text_transform_2(x):
  inner =  [vocab_2[token] for token in tokenizer(x)]

  inner = tosize(inner, 4096, vocab_2)

  return [vocab_2['<BOS>']] + inner + [vocab_2['<EOS>']]

In [ ]:
for i in range(0, len(train_x1)):
  train_x1[i] = text_transform_1(train_x1[i])



In [ ]:
for i in range(0, len(train_x2)):
  train_x2[i] = text_transform_2(train_x2[i])

In [ ]:
train_x1[0]

array([   7,    8,    9, ...,  125, 1097,  758])

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        
        self.fc1_1 = nn.Linear(4096, 128)
        self.fc1_2 = nn.Linear(128, 64)
        
        

        self.fc_final = nn.Linear(128, 2)

    def forward(self, x_1, x_2):

        x_1 = F.relu(self.fc1_1(x_1))
        x_1 = F.relu(self.fc1_2(x_1))

        x_2 = F.relu(self.fc1_1(x_2))
        x_2 = F.relu(self.fc1_2(x_2))

        x = torch.cat((x_1, x_2), dim=1)
        
        x = self.fc_final(x)
        return x

In [ ]:
net = Net()

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.0001)

In [ ]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        super().__init__()
        self.data = data
  
    def __getitem__(self, k):
        return (
            self.data["vectors"][k],
            self.data["labels"][k]
        )
    
    def __len__(self):
        return len(self.data["labels"])

In [ ]:
training_data = list(zip(train_x1, train_x2))

In [ ]:
training_data[0]

(array([   7,    8,    9, ...,  125, 1097,  758]),
 array([   7,    8,    9, ..., 1078,   93, 1079]))

In [ ]:
train_y[0]

0

In [ ]:
training_dataset = MyDataset({
    "vectors": training_data,
    "labels": train_y
})

In [ ]:
valid_x1 = list(valid_x1)

valid_x2 = list(valid_x2)

In [ ]:
for i in range(0, len(valid_x1)):
  valid_x1[i] = text_transform_1(valid_x1[i])

In [ ]:
for i in range(0, len(valid_x2)):
  valid_x2[i] = text_transform_1(valid_x2[i])

In [ ]:
valid_data = list(zip(valid_x1, valid_x2))

In [ ]:
valid_data[0]

(array([   7, 1486,  182, ...,  326,  292,  643]),
 array([ 757, 1005,    2, ..., 1420,  624,   13]))

In [ ]:
valid_y[0]

1

In [ ]:
valid_dataset = MyDataset({
    "vectors": valid_data,
    "labels": valid_y
})

In [ ]:
training_generator = torch.utils.data.DataLoader(training_dataset)

In [ ]:
valid_generator = torch.utils.data.DataLoader(valid_dataset)

In [ ]:
def accuracy(predictions, labels):
    return torch.mean((predictions == labels).float())

In [ ]:
best_model = None

min_val_loss = 100.0

accs = []
val_accs = []
losses = []
val_losses = []

for epoch in range(15):

    net.train()
    total_loss = 0.0
    total_val_loss = 0.0
    correct = 0.0
    val_correct = 0.0

    for idx, (input, label) in enumerate(training_generator):
        # print(idx)

        # zero the parameter gradients
        optimizer.zero_grad()

        outputs = net(input[0].float(), input[1].float())
        # outputs = torch.argmax(outputs)


        loss = criterion(outputs, label.long())
        total_loss += loss

        correct += accuracy(torch.argmax(outputs, dim=1), label)

        loss.backward()
        optimizer.step()

        # validare
    net.eval()
    with torch.no_grad():
      for idy, (input, label) in enumerate(valid_generator):

        output = net(input[0].float(), input[1].float()) 
        val_loss = criterion(output, label.long())
        total_val_loss += val_loss.item() 

        val_correct += accuracy(torch.argmax(output, dim=1), label)

    if (total_val_loss / len(valid_generator) < min_val_loss):
      min_val_loss = total_val_loss / len(valid_generator)
      print("Best model changed")
      torch.save(net, "best.pt")

    losses.append(total_loss / len(training_generator))
    val_losses.append(total_val_loss / len(valid_generator))

    accs.append((100 * correct / len(training_generator)).item())
    val_accs.append((100 * val_correct / len(valid_generator)).item())

    print(f"epoch: {epoch}, train loss: {total_loss / len(training_generator)}, validation loss: {total_val_loss / len(valid_generator)}\n\t\ttrain accuracy: {100 * correct / len(training_generator)}, validation accuracy: {100 * val_correct / len(valid_generator)}")

print('Finished Training')

In [ ]:
import matplotlib.pyplot as plt

plt.plot(np.arange(0, 15, 1), losses, label="train")
plt.plot(np.arange(0, 15, 1), val_losses, label="validation")
plt.title("Losses - train vs validation")
plt.legend()

In [ ]:
plt.plot(np.arange(0, 15, 1), accs, label="train")
plt.plot(np.arange(0, 15, 1), val_accs, label="validation")
plt.title("Accuracy - train vs validation")
plt.legend()